name: Add Tool
description: Suggest a new cloud security tool for the list
title: "[Add Tool]: "
labels: ["addition"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new tool! Please fill out the information below.

  - type: input
    id: tool-name
    attributes:
      label: Tool Name
      description: Name of the tool
      placeholder: e.g., CloudGuard
    validations:
      required: true

  - type: input
    id: tool-url
    attributes:
      label: Tool URL
      description: GitHub repository or official website
      placeholder: https://github.com/org/repo
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Which category does this tool belong to?
      options:
        - Multi-Cloud CSPM
        - Infrastructure as Code (IaC)
        - Asset Inventory
        - Attack Path Analysis
        - AWS Offensive
        - AWS Defensive
        - AWS IAM Analysis
        - S3 Security
        - Azure Offensive
        - Azure Defensive
        - Azure IAM/Entra ID
        - GCP Offensive
        - GCP Defensive
        - Container/Image Scanning
        - Runtime Security
        - Kubernetes Audit
        - IAM Analysis
        - Secrets Scanning
        - Compliance & Governance
        - Serverless Security
        - Training Labs
        - Other (specify below)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Tool Description
      description: Brief description of what the tool does (one sentence)
      placeholder: Scans AWS environments for security misconfigurations
    validations:
      required: true

  - type: dropdown
    id: license
    attributes:
      label: License
      description: What license is the tool under?
      options:
        - MIT
        - Apache-2.0
        - GPL-2.0
        - GPL-3.0
        - BSD-3-Clause
        - AGPL-3.0
        - Proprietary
        - Other
    validations:
      required: true

  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements Check
      description: Please confirm the tool meets our requirements
      options:
        - label: The tool has been updated within the last 12 months
          required: true
        - label: The tool has documentation or a README
          required: true
        - label: The tool is related to cloud security
          required: true
        - label: I have verified the tool works as described
          required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other relevant information about the tool
      placeholder: Optional
